const App = (() => {
  const games = [['fill_blank','✍️','Fill in the Blank'],['cloze','📖','Cloze'],['translation','🌐','Translation'],['unscramble','🧩','Word Unscramble'],['matching','🔗','Word Matching'],['story','📚','Story'],['sentence_transform','🔄','Sentence Transform'],['taboo','🚫','Taboo']];
  const PFX = 'aihub_';
  function loadPrefs(){try{const p=sessionStorage.getItem(PFX+'prefs');if(p)Object.assign(state.userPrefs,JSON.parse(p))}catch(e){}}
  function savePrefs(){const d=document.querySelector('#deck'),m=document.querySelector('#model'),t=document.querySelector('#term'),df=document.querySelector('#definition'),l=document.querySelector('#level'),c=document.querySelector('#count'),tp=document.querySelector('#topic'),lg=document.querySelector('#language'),nb=document.querySelector('#num_blanks'),fs=document.querySelector('#focus');const p={};if(d)p.deck=d.value;if(m)p.model=m.value;if(t)p.term=t.value;if(df)p.definition=df.value;if(l)p.level=l.value;if(c)p.count=c.value;if(tp)p.topic=tp.value;if(lg)p.language=lg.value;if(nb)p.num_blanks=nb.value;if(fs)p.focus=fs.value;Object.assign(state.userPrefs,p);try{sessionStorage.setItem(PFX+'prefs',JSON.stringify(state.userPrefs))}catch(e){}}
  function restorePrefs(){const p=state.userPrefs;if(p.deck){const e=document.querySelector('#deck');if(e)e.value=p.deck}if(p.model){const e=document.querySelector('#model');if(e)e.value=p.model}if(p.term){const e=document.querySelector('#term');if(e)e.value=p.term}if(p.definition){const e=document.querySelector('#definition');if(e)e.value=p.definition}if(p.level){const e=document.querySelector('#level');if(e)e.value=p.level}if(p.count){const e=document.querySelector('#count');if(e)e.value=p.count}if(p.topic){const e=document.querySelector('#topic');if(e)e.value=p.topic}if(p.language){const e=document.querySelector('#language');if(e)e.value=p.language}if(p.num_blanks){const e=document.querySelector('#num_blanks');if(e)e.value=p.num_blanks}if(p.focus){const e=document.querySelector('#focus');if(e)e.value=p.focus}}
  function clearPrefs(){try{sessionStorage.removeItem(PFX+'prefs')}catch(e){}}
  const state = {route:'home', decks:[], pairs:[], seen:new Set(), exercise:null, index:0, answers:{}, busy:false, history:{}, userPrefs:{}};
  loadPrefs();
  const root=document.querySelector('#app'); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=m=>{const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),3500)};
  const nav=r=>{state.route=r;location.hash=r==='home'?'':r;render()};
  const shell=body=>{state.busy=false;root.innerHTML=`<div class="timer-bar"><span class="timer-label">AI Learning Hub</span><span id="busy-label"></span><button id="close-hub">Đóng Hub</button></div>${body}<div id="loading" class="loading-overlay" hidden><div class="spinner"></div><span id="loading-text">Đang xử lý…</span></div>`;document.querySelector('#loading').hidden=true};
  function setBusy(on,text='Đang tạo bài…'){state.busy=on;const e=document.querySelector('#loading');if(e){e.hidden=!on;document.querySelector('#loading-text').textContent=text}document.querySelectorAll('button,input,select,textarea').forEach(x=>{if(x.id!=='close-hub')x.disabled=on})}
  function home(){shell('<main class="container"><div class="header" style="padding-top:50px"><h1>AI Learning Hub</h1><p>Chọn một game để học từ bộ thẻ Anki</p><div class="api-check"><button class="btn btn-outline" id="test-keys">Kiểm tra API</button><span id="api-result" aria-live="polite"></span></div></div><div class="game-grid">'+games.map(g=>'<button class="game-card" data-game="'+g[0]+'"><div class="icon">'+g[1]+'</div><h3>'+g[2]+'</h3><p>'+getGameDesc(g[0])+'</p></button>').join('')+'</div></main>');bindCommon();document.querySelectorAll('[data-game]').forEach(e=>e.onclick=()=>nav(e.dataset.game));document.querySelector('#test-keys').onclick=testKeys}
  function getGameDesc(id){const m={fill_blank:'Điền từ vào chỗ trống trong câu',cloze:'Điền từ vào đoạn văn có chỗ trống',translation:'Dịch câu từ tiếng Việt sang ngoại ngữ',unscramble:'Sắp xếp từ thành câu hoàn chỉnh',matching:'Nối từ với định nghĩa tương ứng',story:'Đọc truyện và trả lời câu hỏi',sentence_transform:'Biến đổi câu theo yêu cầu ngữ pháp',taboo:'Đoán từ qua mô tả (không dùng từ cấm)'};return m[id]||'Luyện tập tương tác'}
  function source(){return `<section class="config-panel source-panel"><h3>Nguồn từ vựng Anki</h3><label>Tìm deck <input id="deck-search" placeholder="Gõ một phần tên deck…"></label><select id="deck" class="deck-list" size="7"></select><div class="selector-grid"><label>Note type<select id="model"><option>Chọn deck</option></select></label><label>Thuật ngữ<select id="term"><option>Chọn note type</option></select></label><label>Định nghĩa<select id="definition"><option>Chọn note type</option></select></label></div><div class="config-row"><label>Số từ mẫu <input id="sample-limit" type="number" value="20" min="1" max="50"></label><button id="sample" class="btn btn-outline">Lấy mẫu</button><button id="reset-samples" class="btn btn-outline">Làm mới vòng</button></div><p id="source-status" class="source-status">Mẫu được chọn ngẫu nhiên, không lặp trong phiên Hub.</p><details id="sample-preview"><summary>Chưa có mẫu để xem</summary><ol id="sample-list"></ol></details></section>`}
  function controls(id){let max=id==='matching'?12:5,min=id==='matching'?3:1,extra='';if(id==='cloze'){max=5;min=1;extra='<label>Số blank<select id="num_blanks">'+Array.from({length:6},(_,i)=>'<option '+(i+5===5?'selected':'')+'>'+(i+5)+'</option>').join('')+'</select></label>'}if(id==='sentence_transform'){max=1;min=1;extra='<label>Dạng<select id="focus"><option value="voice">Voice (Câu bị động)</option><option value="conditional">Conditional (Câu điều kiện)</option><option value="reported">Reported (Câu tường thuật)</option><option value="comparative">Comparative (So sánh)</option></select></label>'}if(id==='translation'||id==='taboo'){max=1;min=1}return '<section class="config-panel"><div class="selector-grid"><label>Ngôn ngữ<select id="language"><option value="en">English</option><option value="zh">中文 (Chinese)</option></select></label><label>Trình độ<select id="level"><option value="beginner">A1 Beginner</option><option value="elementary">A2 Elementary</option><option value="intermediate" selected>B1 Intermediate</option><option value="upper_intermediate">B2 Upper-intermediate</option><option value="advanced">C1–C2 Advanced</option></select></label><label>Số câu<select id="count">'+Array.from({length:max-min+1},(_,i)=>'<option>'+(i+min)+'</option>').join('')+'</select></label>'+extra+'<label>Chủ đề<input id="topic" value="daily_life"></label></div><button class="btn" id="generate">Tạo bài</button></section>'}
  function game(){const g=games.find(x=>x[0]===state.route);shell(`<main class="container game-page" style="padding-top:50px"><div class="game-header"><button id="back" class="back-btn">← Hub</button><h2>${g[1]} ${g[2]}</h2></div>${source()}${controls(g[0])}<section id="play" class="play-area"></section><section id="history-panel" class="history-panel"></section></main>`);bindCommon();bindSource();restorePrefs();document.querySelector('#back').onclick=()=>{savePrefs();nav('home')};document.querySelector('#generate').onclick=()=>{savePrefs();generate(g[0])};renderHistory(g[0])}
  function renderHistory(id){const h=state.history[id];if(!h||!h.length)return;const panel=document.querySelector('#history-panel');if(!panel)return;panel.innerHTML='<h4>Lịch sử gần đây ('+h.length+'/30)</h4>'+h.slice(0,5).map(x=>'<div class="history-item"><span class="history-time">'+new Date(x.time).toLocaleTimeString('vi-VN')+'</span><span class="history-score">'+(x.score!==undefined?x.score+'/'+x.total+' đúng':'')+'</span></div>').join('')}
  function bindCommon(){document.querySelector('#close-hub').onclick=()=>{clearPrefs();Bridge.send('close_hub')}}
  function options(sel,items,label=x=>x.name){const e=document.querySelector(sel);e.innerHTML='<option value="">-- Chọn --</option>'+items.map(x=>'<option value="'+esc(x.id??x)+'">'+esc(label(x))+'</option>').join('')}
  function drawDecks(q=''){const e=document.querySelector('#deck'),items=state.decks.filter(d=>d.name.toLowerCase().includes(q.toLowerCase()));e.innerHTML=items.map(d=>'<option value="'+d.id+'">'+'\u3000'.repeat(d.level)+esc(d.name)+'</option>').join('')||'<option>Không tìm thấy deck</option>'}
  async function bindSource(){try{state.decks=(await Bridge.sendAsync('list_decks')).decks||[];drawDecks()}catch(e){toast(e.message)}document.querySelector('#deck-search').oninput=e=>drawDecks(e.target.value);document.querySelector('#deck').onchange=loadModels;document.querySelector('#model').onchange=loadFields;document.querySelector('#sample').onclick=sample;document.querySelector('#reset-samples').onclick=()=>{state.seen.clear();state.pairs=[];preview()}}
  async function loadModels(){state.seen.clear();state.pairs=[];try{options('#model',(await Bridge.sendAsync('get_source_models',{deck_id:+document.querySelector('#deck').value})).models||[]);options('#term',[]);options('#definition',[])}catch(e){toast(e.message)}}
  async function loadFields(){state.seen.clear();state.pairs=[];try{const f=(await Bridge.sendAsync('get_source_fields',{model_id:+document.querySelector('#model').value})).fields||[];options('#term',f,x=>x);options('#definition',f,x=>x)}catch(e){toast(e.message)}}
  function request(){const deck_id=+document.querySelector('#deck').value,model_id=+document.querySelector('#model').value,term_field=document.querySelector('#term').value,definition_field=document.querySelector('#definition').value;if(!deck_id||!model_id||!term_field||!definition_field)throw Error('Hãy chọn deck, note type và hai trường.');return{deck_id,model_id,term_field,definition_field,limit:+document.querySelector('#sample-limit').value||20,excluded_pair_keys:[...state.seen]}}
  function preview(){const d=document.querySelector('#sample-preview');d.querySelector('summary').textContent=state.pairs.length?'Xem '+state.pairs.length+' từ mẫu':'Chưa có mẫu để xem';d.querySelector('#sample-list').innerHTML=state.pairs.map(x=>'<li><b>'+esc(x.term)+'</b> — '+esc(x.definition)+'</li>').join('')}
  async function sample(){try{const data=await Bridge.sendAsync('sample_vocab_pairs',request());if(data.exhausted)throw Error('Đã dùng hết mẫu trong vòng này. Bấm Làm mới vòng.');state.pairs=data.pairs||[];state.pairs.forEach(x=>state.seen.add(x.key));document.querySelector('#source-status').textContent=`Đã lấy ${data.total} cặp ngẫu nhiên.`;preview();return !!state.pairs.length}catch(e){toast(e.message);return false}}
  async function generate(id){try{setBusy(true);if(!state.pairs.length&&!await sample())return;const lang=document.querySelector('#language');const opts={gamemode:id,language:lang?lang.value:'en',level:document.querySelector('#level').value,count:+document.querySelector('#count').value,topic:document.querySelector('#topic').value,vocab_pairs:state.pairs};if(id==='cloze'){const nb=document.querySelector('#num_blanks');if(nb)opts.num_blanks=+nb.value}if(id==='sentence_transform'){const fs=document.querySelector('#focus');if(fs)opts.focus=fs.value}state.exercise=await Bridge.sendAsync('generate',opts);state.index=0;state.answers={};addHistory(id,state.exercise);play(id)}catch(e){toast(e.message)}finally{setBusy(false)}}
  function addHistory(id,data){if(!state.history[id])state.history[id]=[];state.history[id].unshift({time:Date.now(),data});if(state.history[id].length>30)state.history[id].length=30}
  const buttons=(opts,name,chosen)=>opts.map((o,i)=>`<button class="option-btn ${chosen===i?'selected':''}" data-choice="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('');

  /* ---- PLAY: route to renderers ---- */
  function play(id){const d=document.querySelector('#play'),x=state.exercise;if(!x)return;state.answers={};
    if(id==='fill_blank')renderFillBlank(x);
    else if(id==='cloze')renderCloze(x);
    else if(id==='matching')renderMatching(x);
    else if(id==='unscramble')renderUnscrambleAll(x);
    else if(id==='story')renderStory(x);
    else if(id==='translation')renderTranslation(x);
    else if(id==='sentence_transform')renderSentenceTransform(x);
    else if(id==='taboo')renderTaboo(x);
  }

  /* ---- FILL-BLANK: all questions vertical ---- */
  function renderFillBlank(x){const d=document.querySelector('#play');const cards=x.questions.map((q,i)=>{return '<div class="question-card fade-in"><div class="q-number">Câu '+(i+1)+'/'+x.questions.length+'</div><div class="q-text">'+esc(q.sentence_with_blank)+'</div><div class="q-translation">'+esc(q.sentence_translation||'')+'</div><div id="choices-'+i+'">'+buttons(q.options,'fill',state.answers[i])+'</div><button class="btn" id="grade-'+i+'">Chấm điểm</button><div id="feedback-'+i+'"></div></div>'}).join('');d.innerHTML=cards;x.questions.forEach((q,i)=>{document.querySelectorAll('#choices-'+i+' [data-choice]').forEach(b=>b.onclick=()=>{state.answers[i]=+b.dataset.choice;renderFillBlank(x)});document.querySelector('#grade-'+i).onclick=()=>{let s=state.answers[i];const ok=s===q.correct_index,fb=document.querySelector('#feedback-'+i);let html='<div class="feedback '+(ok?'good':'bad')+'"><b>'+(ok?'Chính xác!':'Chưa đúng.')+'</b><p>Đáp án: '+esc(q.options[q.correct_index])+'</p><p>'+esc(q.explanation_short||q.semantic||'')+'</p>';if(q.word_meaning)html+='<p>📖 <b>Nghĩa từ:</b> '+esc(q.word_meaning)+'</p>';if(q.usage_example)html+='<p>📝 <b>Ví dụ:</b> '+esc(q.usage_example)+'</p>';if(q.sentence_translation)html+='<p>🌐 <b>Dịch:</b> '+esc(q.sentence_translation)+'</p>';html+='</div>';fb.innerHTML=html}})
  }

  /* ---- CLOZE: paragraph with selects + word bank ---- */
  function renderCloze(x){const d=document.querySelector('#play');const wordChips=x.blanks.map((b,i)=>{const vn=b.meaning_in_vietnamese?' - '+b.meaning_in_vietnamese:'';return '<span class="word-preview-item" data-blank="'+i+'" data-word="'+esc(b.correct_word)+'">'+(i+1)+'. '+esc(b.correct_word)+esc(vn)+'</span>'}).join('');const blankSelects=x.blanks.map((b,i)=>{return '<label class="cloze-blank-label">Blank '+(i+1)+'<select data-blank="'+i+'"><option value="">-- chọn --</option>'+b.options.map((o,j)=>'<option value="'+j+'">'+esc(o)+'</option>').join('')+'</select></label>'}).join('');d.innerHTML='<div class="question-card"><div class="q-text">'+esc(x.paragraph_with_blanks)+'</div>'+(x.sentence_meaning?'<div class="q-translation">'+esc(x.sentence_meaning)+'</div>':'')+'<div class="word-preview"><h4>Từ để chọn ('+x.blanks.length+' từ):</h4><div class="word-preview-list">'+wordChips+'</div></div><div class="cloze-blanks">'+blankSelects+'</div><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>';document.querySelectorAll('.word-preview-item').forEach(e=>e.onclick=()=>{const idx=+e.dataset.blank;const sel=document.querySelector('select[data-blank="'+idx+'"]');if(!sel)return;const correctWord=e.dataset.word;const optIdx=Array.from(sel.options).findIndex(o=>o.text.toLowerCase()===correctWord.toLowerCase());if(optIdx>=0){sel.value=optIdx;sel.classList.add('auto-filled')}});document.querySelector('#grade').onclick=()=>gradeCloze(x)}
  function gradeCloze(x){let score=0;document.querySelectorAll('[data-blank]').forEach(e=>{let b=x.blanks[+e.dataset.blank],ok=+e.value===b.correct_index;score+=ok;e.classList.add(ok?'correct':'wrong')});const explanations=x.blanks.map((b,i)=>{const correct=b.options[b.correct_index];const vn=b.meaning_in_vietnamese?' — '+b.meaning_in_vietnamese:'';return '<p>'+(i+1)+'. <b>'+esc(correct)+'</b>: '+esc(b.explanation_short||b.explanation||'')+esc(vn)+'</p>'}).join('');const meaning=x.sentence_meaning?'<p>🌐 '+esc(x.sentence_meaning)+'</p>':'';document.querySelector('#feedback').innerHTML='<div class="feedback '+(score===x.blanks.length?'good':'bad')+'"><b>'+score+'/'+x.blanks.length+' đúng</b>'+meaning+explanations+'<button class="btn" onclick="App.retry()">Thử lại</button></div>'}

  /* ---- MATCHING: vertical columns ---- */
  function renderMatching(x){const d=document.querySelector('#play');d.innerHTML='<div class="question-card"><p>Chọn từ, rồi chọn nghĩa tương ứng.</p><div class="match-columns"><div id="left" class="match-col">'+x.left_column.map(t=>'<button class="match-item" data-term="'+esc(t)+'">'+esc(t)+'</button>').join('')+'</div><div id="right" class="match-col">'+x.right_column.map(t=>'<button class="match-item" data-def="'+esc(t)+'">'+esc(t)+'</button>').join('')+'</div></div><p id="match-status"></p><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>';let term=null,matches={};document.querySelectorAll('[data-term]').forEach(e=>e.onclick=()=>{term=e.dataset.term;document.querySelectorAll('[data-term].selected').forEach(x=>x.classList.remove('selected'));e.classList.add('selected')});document.querySelectorAll('[data-def]').forEach(e=>e.onclick=()=>{if(!term)return;let pair=x.pairs.find(p=>p.term===term);let ok=pair?.definition===e.dataset.def;e.classList.add(ok?'matched':'wrong');if(ok){matches[term]=e.dataset.def;document.querySelector('[data-term="'+CSS.escape(term)+'"]').classList.add('matched');document.querySelector('[data-term="'+CSS.escape(term)+'"]').classList.remove('selected');term=null}else{setTimeout(()=>e.classList.remove('wrong'),600)}const done=Object.keys(matches).length;document.querySelector('#match-status').textContent=done+'/'+x.pairs.length+' cặp đúng';if(done===x.pairs.length)document.querySelector('#match-status').style.color='var(--success)'});document.querySelector('#grade').onclick=()=>{let total=x.pairs.length,allDone=Object.keys(matches).length;document.querySelector('#feedback').innerHTML='<div class="feedback '+(allDone===total?'good':'bad')+'"><b>'+allDone+'/'+total+' đúng</b><button class="btn" id="retry">Thử lại</button></div>';document.querySelector('#retry').onclick=()=>{state.answers={};play(state.route)}}}

  /* ---- UNSCRAMBLE: all questions vertical, white words ---- */
  function renderUnscrambleAll(x){const d=document.querySelector('#play');d.innerHTML=x.questions.map((q,i)=>{return'<div class="question-card unscramble-card fade-in"><p class="hint-text">'+esc(q.hint)+'</p>'+(q.translation?'<p class="q-translation">'+esc(q.translation)+'</p>':'')+'<div id="us-'+i+'" class="unscramble-area"></div><button class="btn" id="ugrade-'+i+'">Chấm điểm</button><div id="ufeedback-'+i+'"></div></div>'}).join('');x.questions.forEach((q,i)=>{renderUnscrambleSingle(q,i,x.questions)});}
  function renderUnscrambleSingle(q,i,all){const chosen=[];const area=document.querySelector('#us-'+i);function draw(){area.innerHTML='<div class="drop-zone">'+chosen.map(w=>'<button class="drag-word" data-back="'+esc(w)+'">'+esc(w)+'</button>').join('')+'</div><div class="drag-container">'+q.shuffled_words.filter((w,j)=>!chosen.includes(w)||chosen.filter(x=>x===w).length<q.shuffled_words.slice(0,j+1).filter(x=>x===w).length).map(w=>'<button class="drag-word" data-word="'+esc(w)+'">'+esc(w)+'</button>').join('')+'</div>';area.querySelectorAll('[data-word]').forEach(e=>e.onclick=()=>{chosen.push(e.dataset.word);draw()});area.querySelectorAll('[data-back]').forEach(e=>e.onclick=()=>{chosen.splice(chosen.indexOf(e.dataset.back),1);draw()})}draw();document.querySelector('#ugrade-'+i).onclick=()=>{const ok=chosen.join(' ').toLowerCase()===q.correct_sentence.toLowerCase();const fb=document.querySelector('#ufeedback-'+i);let html='<div class="feedback '+(ok?'good':'bad')+'"><b>'+(ok?'Chính xác!':'Chưa đúng.')+'</b><p>'+esc(q.correct_sentence)+'</p>';if(q.sentence_meaning)html+='<p>🌐 '+esc(q.sentence_meaning)+'</p>';if(q.key_vocab)html+=q.key_vocab.map(k=>'<p>📖 <b>'+esc(k.word)+'</b>: '+esc(k.meaning)+'</p>').join('');html+='</div>';fb.innerHTML=html}}

  /* ---- STORY: read + comprehension questions ---- */
  function renderStory(x){const d=document.querySelector('#play');d.innerHTML='<div class="question-card"><div class="story-text">'+esc(x.story)+'</div>'+x.comprehension_questions.map((q,i)=>'<div class="comprehension-q"><p>'+(i+1)+'. '+esc(q.question)+'</p>'+buttons(q.options,'story',state.answers[i])+'</div>').join('')+'<button class="btn" id="grade">Chấm điểm toàn bộ</button><div id="feedback"></div></div>';document.querySelectorAll('[data-choice]').forEach((e,n)=>e.onclick=()=>{let q=Math.floor(n/4);state.answers[q]=+e.dataset.choice;renderStory(x)});document.querySelector('#grade').onclick=()=>{let n=x.comprehension_questions.filter((q,i)=>state.answers[i]===q.correct_index).length;document.querySelector('#feedback').innerHTML='<div class="feedback '+(n===x.comprehension_questions.length?'good':'bad')+'"><b>'+n+'/'+x.comprehension_questions.length+' đúng</b><button class="btn" id="retry">Thử lại</button></div>';document.querySelector('#retry').onclick=()=>{state.answers={};play(state.route)}}}

  /* ---- TRANSLATION: 1 sentence, detailed AI grade ---- */
  function renderTranslation(x){const q=x.sentences[0];document.querySelector('#play').innerHTML='<div class="question-card"><p class="q-text">'+esc(q.source_text)+'</p><textarea id="answer" placeholder="Nhập bản dịch…"></textarea><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>';document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'translation',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,expected:q.target_text,source_text:q.source_text});const fb=document.querySelector('#feedback');let html='<div class="feedback '+(r.correct?'good':'bad')+'"><b>'+(r.correct?'Chính xác!':'Cần cải thiện')+'</b><p>'+esc(r.explanation||r.feedback||'')+'</p><p>Đáp án: '+esc(q.target_text)+'</p>';if(q.detailed_feedback){const df=q.detailed_feedback;html+='<hr>';if(df.word_by_word){html+='<p><b>Phân tích từ:</b></p>'+df.word_by_word.map(w=>'<p>• <b>'+esc(w.word)+'</b>: '+esc(w.translation)+(w.notes?' — '+esc(w.notes):'')+'</p>').join('')}if(df.common_mistakes&&df.common_mistakes.length){html+='<p><b>Lỗi thường gặp:</b></p><ul>'+df.common_mistakes.map(m=>'<li>'+esc(m)+'</li>').join('')+'</ul>'}if(df.alternative_translations&&df.alternative_translations.length){html+='<p><b>Cách dịch khác:</b></p><ul>'+df.alternative_translations.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>'}if(df.improvement_tips)html+='<p><b>Gợi ý:</b> '+esc(df.improvement_tips)+'</p>'}html+='<button class="btn" id="retry-trans">Làm lại</button></div>';fb.innerHTML=html;document.querySelector('#retry-trans').onclick=()=>{state.answers={};play(state.route)}}catch(e){toast(e.message)}finally{setBusy(false)}}}

  /* ---- SENTENCE TRANSFORM: 1 sentence, focus selector, detailed ---- */
  function renderSentenceTransform(x){const q=x.questions[0];document.querySelector('#play').innerHTML='<div class="question-card"><p class="q-text"><b>Yêu cầu:</b> '+esc(q.instruction)+'</p><p class="q-text"><b>Câu gốc:</b> '+esc(q.original_sentence)+'</p><textarea id="answer" placeholder="Nhập câu trả lời..."></textarea><button class="btn primary" id="grade">Chấm điểm</button><div id="feedback"></div></div>';document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'sentence_transform',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,expected:q.expected_answer,instruction:q.instruction,original:q.original_sentence});const fb=document.querySelector('#feedback');let html='<div class="feedback '+(r.correct?'good':'bad')+'"><b>'+(r.correct?'Chính xác!':'Cần cải thiện')+'</b><p>'+esc(r.explanation||r.feedback||'')+'</p><p>Đáp án: '+esc(q.expected_answer)+'</p>';if(q.detailed_explanation){const de=q.detailed_explanation;html+='<hr><p><b>Giải thích:</b> '+esc(de.rule_description||q.grammar_rule||'')+'</p>';if(de.step_by_step&&de.step_by_step.length)html+='<p><b>Các bước:</b></p><ol>'+de.step_by_step.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>';if(de.common_errors&&de.common_errors.length)html+='<p><b>Lỗi thường gặp:</b></p><ul>'+de.common_errors.map(e=>'<li>'+esc(e)+'</li>').join('')+'</ul>';if(de.comparison)html+='<p><b>So sánh:</b> '+esc(de.comparison)+'</p>'}html+='<button class="btn" id="retry-trans">Làm lại</button></div>';fb.innerHTML=html;document.querySelector('#retry-trans').onclick=()=>{state.answers={};play(state.route)}}catch(e){toast(e.message)}finally{setBusy(false)}}}

  /* ---- TABOO: 1 round, concept → English, AI grade ---- */
  function renderTaboo(x){const q=x.rounds[0];document.querySelector('#play').innerHTML='<div class="question-card taboo-card fade-in"><div class="secret-word">???</div><div class="forbidden">'+q.forbidden_words.map(w=>'<span>🚫 '+esc(w)+'</span>').join('')+'</div><div class="description">'+esc(q.ai_description)+'</div><textarea id="answer" placeholder="Nhập từ bạn đoán bằng '+(state.userPrefs.language||'en')+'..."></textarea><button class="btn primary" id="grade">Chấm điểm</button><div id="feedback"></div></div>';document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'taboo',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,secret_word:q.secret_word});document.querySelector('#feedback').innerHTML='<div class="feedback '+(r.correct?'good':'bad')+'"><b>'+(r.correct?'Chính xác!':'Sai rồi')+'</b><p>'+esc(r.explanation||r.feedback||'')+'</p><p>Đáp án: <b>'+esc(q.secret_word)+'</b></p><p>📖 <b>Nghĩa:</b> '+esc(q.ai_description)+'</p><button class="btn" id="retry-trans">Làm lại</button></div>';document.querySelector('#retry-trans').onclick=()=>{state.answers={};play(state.route)}}catch(e){toast(e.message)}finally{setBusy(false)}}}

  /* ---- API KEY TESTER ---- */
  async function testKeys(){const button=document.querySelector('#test-keys'),out=document.querySelector('#api-result');try{button.innerHTML='<span class="button-spinner"></span> Đang kiểm tra…';setBusy(true,'Đang kiểm tra API…');const data=await Bridge.sendAsync('test_all_keys');const results=data.results||[],ok=results.filter(item=>item.ok).length;out.innerHTML=results.map(item=>`<span class="api-key-status ${item.ok?'ok':'fail'}">Key ${item.key} ${item.ok?'✓':'✕'}</span>`).join('')+` <b>${ok}/${results.length} hoạt động</b>`}catch(e){out.textContent=`Không thể kiểm tra: ${e.message}`}finally{setBusy(false);button.innerHTML='Kiểm tra API'}}

  function render(){state.route==='home'?home():game()}
  return {start:render,navigate:nav,retry:()=>{state.answers={};play(state.route)}}
})();window.App=App;document.addEventListener('DOMContentLoaded',App.start);
