const App = (() => {
  const games = [['fill_blank','✍️','Fill in the Blank'],['cloze','📖','Cloze'],['translation','🌐','Translation'],['unscramble','🧩','Word Unscramble'],['matching','🔗','Word Matching'],['story','📚','Story'],['sentence_transform','🔄','Sentence Transform'],['taboo','🚫','Taboo']];
  const state = {route:'home', decks:[], pairs:[], seen:new Set(), exercise:null, index:0, answers:{}, busy:false, history:{}, userPrefs:{}};
  const root=document.querySelector('#app'); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]));
  const toast=m=>{const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),3500)};
  const nav=r=>{state.route=r;location.hash=r==='home'?'':r;render()};
  const shell=body=>{state.busy=false;root.innerHTML=`<div class="timer-bar"><span class="timer-label">AI Learning Hub</span><span id="busy-label"></span><button id="close-hub">Đóng Hub</button></div>${body}<div id="loading" class="loading-overlay" hidden><div class="spinner"></div><span id="loading-text">Đang xử lý…</span></div>`;document.querySelector('#loading').hidden=true};
  function setBusy(on,text='Đang tạo bài…'){state.busy=on;const e=document.querySelector('#loading');if(e){e.hidden=!on;document.querySelector('#loading-text').textContent=text}document.querySelectorAll('button,input,select,textarea').forEach(x=>{if(x.id!=='close-hub')x.disabled=on})}
  function home(){shell(`<main class="container"><div class="header" style="padding-top:50px"><h1>AI Learning Hub</h1><p>Chọn một game để học từ bộ thẻ Anki</p><div class="api-check"><button class="btn btn-outline" id="test-keys">Kiểm tra API</button><span id="api-result" aria-live="polite"></span></div></div><div class="game-grid">${games.map(g=>`<button class="game-card" data-game="${g[0]}"><div class="icon">${g[1]}</div><h3>${g[2]}</h3><p>${getGameDesc(g[0])}</p></button>`).join('')}</div></main>`);bindCommon();document.querySelectorAll('[data-game]').forEach(e=>e.onclick=()=>nav(e.dataset.game));document.querySelector('#test-keys').onclick=testKeys}
  function getGameDesc(id){const m={fill_blank:'Điền từ vào chỗ trống trong câu',cloze:'Điền từ vào đoạn văn có chỗ trống',translation:'Dịch câu từ tiếng Việt sang ngoại ngữ',unscramble:'Sắp xếp từ thành câu hoàn chỉnh',matching:'Nối từ với định nghĩa tương ứng',story:'Đọc truyện và trả lời câu hỏi',sentence_transform:'Biến đổi câu theo yêu cầu ngữ pháp',taboo:'Đoán từ qua mô tả (không dùng từ cấm)'};return m[id]||'Luyện tập tương tác'}
  function source(){return `<section class="config-panel source-panel"><h3>Nguồn từ vựng Anki</h3><label>Tìm deck <input id="deck-search" placeholder="Gõ một phần tên deck…"></label><select id="deck" class="deck-list" size="7"></select><div class="selector-grid"><label>Note type<select id="model"><option>Chọn deck</option></select></label><label>Thuật ngữ<select id="term"><option>Chọn note type</option></select></label><label>Định nghĩa<select id="definition"><option>Chọn note type</option></select></label></div><div class="config-row"><label>Số từ mẫu <input id="sample-limit" type="number" value="20" min="1" max="50"></label><button id="sample" class="btn btn-outline">Lấy mẫu</button><button id="reset-samples" class="btn btn-outline">Làm mới vòng</button></div><p id="source-status" class="source-status">Mẫu được chọn ngẫu nhiên, không lặp trong phiên Hub.</p><details id="sample-preview"><summary>Chưa có mẫu để xem</summary><ol id="sample-list"></ol></details></section>`}
  function controls(id){let max=id==='matching'?12:5,min=id==='matching'?3:1;return `<section class="config-panel"><div class="selector-grid"><label>Ngôn ngữ<select id="language"><option value="en">English</option><option value="zh">中文 (Chinese)</option></select></label><label>Trình độ<select id="level"><option value="beginner">A1 Beginner</option><option value="elementary">A2 Elementary</option><option value="intermediate" selected>B1 Intermediate</option><option value="upper_intermediate">B2 Upper-intermediate</option><option value="advanced">C1–C2 Advanced</option></select></label><label>Số câu<select id="count">${Array.from({length:max-min+1},(_,i)=>`<option>${i+min}</option>`).join('')}</select></label><label>Chủ đề<input id="topic" value="daily_life"></label></div><button class="btn" id="generate">Tạo bài</button></section>`}
  function savePrefs(){const d=document.querySelector('#deck'),m=document.querySelector('#model'),t=document.querySelector('#term'),df=document.querySelector('#definition'),l=document.querySelector('#level'),c=document.querySelector('#count'),tp=document.querySelector('#topic'),lg=document.querySelector('#language');if(d)state.userPrefs.deck=d.value;if(m)state.userPrefs.model=m.value;if(t)state.userPrefs.term=t.value;if(df)state.userPrefs.definition=df.value;if(l)state.userPrefs.level=l.value;if(c)state.userPrefs.count=c.value;if(tp)state.userPrefs.topic=tp.value;if(lg)state.userPrefs.language=lg.value}
  function restorePrefs(){const p=state.userPrefs;if(p.deck)document.querySelector('#deck').value=p.deck;if(p.model)document.querySelector('#model').value=p.model;if(p.term)document.querySelector('#term').value=p.term;if(p.definition)document.querySelector('#definition').value=p.definition;if(p.level)document.querySelector('#level').value=p.level;if(p.count)document.querySelector('#count').value=p.count;if(p.topic)document.querySelector('#topic').value=p.topic;if(p.language)document.querySelector('#language').value=p.language}
  function game(){const g=games.find(x=>x[0]===state.route);shell(`<main class="container game-page" style="padding-top:50px"><div class="game-header"><button id="back" class="back-btn">← Hub</button><h2>${g[1]} ${g[2]}</h2></div>${source()}${controls(g[0])}<section id="play" class="play-area"></section><section id="history-panel" class="history-panel"></section></main>`);bindCommon();bindSource();restorePrefs();document.querySelector('#back').onclick=()=>{savePrefs();nav('home')};document.querySelector('#generate').onclick=()=>{savePrefs();generate(g[0])};renderHistory(g[0])}
  function renderHistory(id){const h=state.history[id];if(!h||!h.length)return;const panel=document.querySelector('#history-panel');if(!panel)return;panel.innerHTML=`<h4>Lịch sử gần đây (${h.length})</h4>${h.slice(0,5).map(x=>`<div class="history-item">${new Date(x.time).toLocaleTimeString('vi-VN')} — ${getGameDesc(id)}</div>`).join('')}`}
  function bindCommon(){document.querySelector('#close-hub').onclick=()=>Bridge.send('close_hub')}
  function options(sel,items,label=x=>x.name){const e=document.querySelector(sel);e.innerHTML=`<option value="">-- Chọn --</option>${items.map(x=>`<option value="${esc(x.id??x)}">${esc(label(x))}</option>`).join('')}`}
  function drawDecks(q=''){const e=document.querySelector('#deck'),items=state.decks.filter(d=>d.name.toLowerCase().includes(q.toLowerCase()));e.innerHTML=items.map(d=>`<option value="${d.id}">${'　'.repeat(d.level)}${esc(d.name)}</option>`).join('')||'<option>Không tìm thấy deck</option>'}
  async function bindSource(){try{state.decks=(await Bridge.sendAsync('list_decks')).decks||[];drawDecks()}catch(e){toast(e.message)}document.querySelector('#deck-search').oninput=e=>drawDecks(e.target.value);document.querySelector('#deck').onchange=loadModels;document.querySelector('#model').onchange=loadFields;document.querySelector('#sample').onclick=sample;document.querySelector('#reset-samples').onclick=()=>{state.seen.clear();state.pairs=[];preview()}}
  async function loadModels(){state.seen.clear();state.pairs=[];try{options('#model',(await Bridge.sendAsync('get_source_models',{deck_id:+document.querySelector('#deck').value})).models||[]);options('#term',[]);options('#definition',[])}catch(e){toast(e.message)}}
  async function loadFields(){state.seen.clear();state.pairs=[];try{const f=(await Bridge.sendAsync('get_source_fields',{model_id:+document.querySelector('#model').value})).fields||[];options('#term',f,x=>x);options('#definition',f,x=>x)}catch(e){toast(e.message)}}
  function request(){const deck_id=+document.querySelector('#deck').value,model_id=+document.querySelector('#model').value,term_field=document.querySelector('#term').value,definition_field=document.querySelector('#definition').value;if(!deck_id||!model_id||!term_field||!definition_field)throw Error('Hãy chọn deck, note type và hai trường.');return{deck_id,model_id,term_field,definition_field,limit:+document.querySelector('#sample-limit').value||20,excluded_pair_keys:[...state.seen]}}
  function preview(){const d=document.querySelector('#sample-preview');d.querySelector('summary').textContent=state.pairs.length?`Xem ${state.pairs.length} từ mẫu`:'Chưa có mẫu để xem';d.querySelector('#sample-list').innerHTML=state.pairs.map(x=>`<li><b>${esc(x.term)}</b> — ${esc(x.definition)}</li>`).join('')}
  async function sample(){try{const data=await Bridge.sendAsync('sample_vocab_pairs',request());if(data.exhausted)throw Error('Đã dùng hết mẫu trong vòng này. Bấm Làm mới vòng.');state.pairs=data.pairs||[];state.pairs.forEach(x=>state.seen.add(x.key));document.querySelector('#source-status').textContent=`Đã lấy ${data.total} cặp ngẫu nhiên.`;preview();return !!state.pairs.length}catch(e){toast(e.message);return false}}
  async function generate(id){try{setBusy(true);if(!state.pairs.length&&!await sample())return;const lang=document.querySelector('#language');state.exercise=await Bridge.sendAsync('generate',{gamemode:id,language:lang?lang.value:'en',level:document.querySelector('#level').value,count:+document.querySelector('#count').value,topic:document.querySelector('#topic').value,vocab_pairs:state.pairs});state.index=0;state.answers={};addHistory(id,state.exercise);play(id)}catch(e){toast(e.message)}finally{setBusy(false)}}
  function addHistory(id,data){if(!state.history[id])state.history[id]=[];state.history[id].unshift({time:Date.now(),data});if(state.history[id].length>30)state.history[id].length=30}
  const buttons=(opts,name,chosen)=>opts.map((o,i)=>`<button class="option-btn ${chosen===i?'selected':''}" data-choice="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('');
  function play(id){const d=document.querySelector('#play'),x=state.exercise;if(!x)return;let html='';if(id==='fill_blank'){let q=x.questions[state.index];html=`<div class="question-card"><div class="q-number">Câu ${state.index+1}/${x.questions.length}</div><div class="q-text">${esc(q.sentence_with_blank)}</div><div id="choices">${buttons(q.options,'fill',state.answers.choice)}</div><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;d.innerHTML=html;bindChoice(q,id)}else if(id==='cloze'){d.innerHTML=`<div class="question-card"><div class="q-text">${esc(x.paragraph_with_blanks)}</div><div class="word-preview"><h4>Từ để chọn (${x.blanks.length} từ):</h4><div class="word-preview-list">${x.blanks.map(b=>`<span class="word-preview-item">${esc(b.options[b.correct_index])}</span>`).join('')}</div></div>${x.blanks.map((b,i)=>`<label>Blank ${i+1}<select data-blank="${i}"><option value="">-- chọn --</option>${b.options.map((o,j)=>`<option value="${j}">${esc(o)}</option>`).join('')}</select></label>`).join('')}<button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelector('#grade').onclick=()=>gradeCloze(x)}else if(id==='matching'){renderMatching(x)}else if(id==='unscramble'){renderUnscramble(x.questions[state.index])}else if(id==='story'){renderStory(x)}else if(id==='translation'){renderTranslation(x)}else if(id==='sentence_transform'){renderSentenceTransform(x)}else if(id==='taboo'){renderTaboo(x)}}
  function bindChoice(q,id){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{state.answers.choice=+b.dataset.choice;play(id)});document.querySelector('#grade').onclick=()=>{let s=state.answers.choice,ok=s===q.correct_index,all=state.exercise.questions;document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Chính xác!':'Chưa đúng.'}</b><p>Đáp án: ${esc(q.options[q.correct_index])}</p><p>${esc(q.explanation_short||q.semantic||'')}</p><button class="btn" id="next">${state.index+1<all.length?'Câu tiếp theo':'Thử lại'}</button></div>`;document.querySelector('#next').onclick=()=>{state.index=(state.index+1)%all.length;state.answers={};play(id)}}}
  function gradeCloze(x){let score=0;document.querySelectorAll('[data-blank]').forEach(e=>{let b=x.blanks[+e.dataset.blank],ok=+e.value===b.correct_index;score+=ok;e.classList.add(ok?'correct':'wrong')});document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${score}/${x.blanks.length} đúng</b><button class="btn" onclick="window.App.retry()">Thử lại</button></div>`}
  function renderMatching(x){const d=document.querySelector('#play');d.innerHTML=`<div class="question-card"><p>Chọn từ, rồi chọn nghĩa tương ứng.</p><div class="match-columns"><div id="left">${x.left_column.map(t=>`<button class="match-item" data-term="${esc(t)}">${esc(t)}</button>`).join('')}</div><div id="right">${x.right_column.map(t=>`<button class="match-item" data-def="${esc(t)}">${esc(t)}</button>`).join('')}</div></div><p id="match-status"></p></div>`;let term=null,done=0;document.querySelectorAll('[data-term]').forEach(e=>e.onclick=()=>{term=e.dataset.term;e.classList.add('selected')});document.querySelectorAll('[data-def]').forEach(e=>e.onclick=()=>{if(!term)return;let pair=x.pairs.find(p=>p.term===term);let ok=pair?.definition===e.dataset.def;e.classList.add(ok?'matched':'wrong');if(ok){done++;document.querySelector(`[data-term="${CSS.escape(term)}"]`).classList.add('matched');term=null}document.querySelector('#match-status').textContent=`${done}/${x.pairs.length} cặp đúng`})}
  function renderUnscramble(q){let chosen=[];const d=document.querySelector('#play');const draw=()=>{d.innerHTML=`<div class="question-card"><p>${esc(q.hint)}</p><div class="drop-zone">${chosen.map(w=>`<button class="drag-word" data-back="${esc(w)}">${esc(w)}</button>`).join('')}</div><div class="drag-container">${q.shuffled_words.filter((w,i)=>!chosen.includes(w)||chosen.filter(x=>x===w).length<q.shuffled_words.slice(0,i+1).filter(x=>x===w).length).map(w=>`<button class="drag-word" data-word="${esc(w)}">${esc(w)}</button>`).join('')}</div><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelectorAll('[data-word]').forEach(e=>e.onclick=()=>{chosen.push(e.dataset.word);draw()});document.querySelectorAll('[data-back]').forEach(e=>e.onclick=()=>{chosen.splice(chosen.indexOf(e.dataset.back),1);draw()});document.querySelector('#grade').onclick=()=>{let ok=chosen.join(' ').toLowerCase()===q.correct_sentence.toLowerCase();document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${ok?'Chính xác!':'Chưa đúng.'}</b><p>${esc(q.correct_sentence)}</p></div>`}};draw()}
  function renderStory(x){const d=document.querySelector('#play');d.innerHTML=`<div class="question-card"><div class="story-text">${esc(x.story)}</div>${x.comprehension_questions.map((q,i)=>`<div><p>${i+1}. ${esc(q.question)}</p>${buttons(q.options,'story',state.answers[i])}</div>`).join('')}<button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelectorAll('[data-choice]').forEach((e,n)=>e.onclick=()=>{let q=Math.floor(n/4);state.answers[q]=+e.dataset.choice;renderStory(x)});document.querySelector('#grade').onclick=()=>{let n=x.comprehension_questions.filter((q,i)=>state.answers[i]===q.correct_index).length;document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${n}/${x.comprehension_questions.length} đúng</b></div>`}}
  function renderTranslation(x){const q=x.sentences[state.index];document.querySelector('#play').innerHTML=`<div class="question-card"><p class="q-text">${esc(q.source_text)}</p><textarea id="answer" placeholder="Nhập bản dịch…"></textarea><button class="btn" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'translation',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,expected:q.target_text,source_text:q.source_text});document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${r.correct?'Chính xác!':'Cần cải thiện'}</b><p>${esc(r.explanation||r.feedback||'')}</p><p>Đáp án: ${esc(q.target_text)}</p></div>`}catch(e){toast(e.message)}finally{setBusy(false)}}}
  function renderSentenceTransform(x){const q=x.questions[state.index];document.querySelector('#play').innerHTML=`<div class="question-card"><p class="q-text">${esc(q.instruction)}</p><p class="q-text">${esc(q.original_sentence)}</p><textarea id="answer" placeholder="Nhập câu trả lời..."></textarea><button class="btn primary" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'sentence_transform',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,expected:q.expected_answer,instruction:q.instruction,original:q.original_sentence});document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${r.correct?'Chính xác!':'Cần cải thiện'}</b><p>${esc(r.explanation||r.feedback||'')}</p><p>Đáp án: ${esc(q.expected_answer)}</p></div>`}catch(e){toast(e.message)}finally{setBusy(false)}}}
  function renderTaboo(x){const q=x.rounds[state.index];document.querySelector('#play').innerHTML=`<div class="question-card"><p class="q-text">${esc(q.ai_description)}</p><textarea id="answer" placeholder="Nhập từ bạn đoán..."></textarea><button class="btn primary" id="grade">Chấm điểm</button><div id="feedback"></div></div>`;document.querySelector('#grade').onclick=async()=>{try{setBusy(true,'Đang chấm điểm…');let r=await Bridge.sendAsync('ai_grade',{gamemode:'taboo',level:document.querySelector('#level').value,user_answer:document.querySelector('#answer').value,secret_word:q.secret_word});document.querySelector('#feedback').innerHTML=`<div class="feedback"><b>${r.correct?'Chính xác!':'Cần cải thiện'}</b><p>${esc(r.explanation||r.feedback||'')}</p><p>Đáp án: ${esc(q.secret_word)}</p></div>`}catch(e){toast(e.message)}finally{setBusy(false)}}}
  async function testKeys(){const button=document.querySelector('#test-keys'),out=document.querySelector('#api-result');try{button.innerHTML='<span class="button-spinner"></span> Đang kiểm tra…';setBusy(true,'Đang kiểm tra API…');const data=await Bridge.sendAsync('test_all_keys');const results=data.results||[],ok=results.filter(item=>item.ok).length;out.innerHTML=results.map(item=>`<span class="api-key-status ${item.ok?'ok':'fail'}">Key ${item.key} ${item.ok?'✓':'✕'}</span>`).join('')+` <b>${ok}/${results.length} hoạt động</b>`}catch(e){out.textContent=`Không thể kiểm tra: ${e.message}`}finally{setBusy(false);button.innerHTML='Kiểm tra API'}}
  function render(){state.route==='home'?home():game()}
  return {start:render,navigate:nav,retry:()=>{state.answers={};play(state.route)}}
})();window.App=App;document.addEventListener('DOMContentLoaded',App.start);